# Generated by Django 3.1.1 on 2020-09-08 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPtest', '0002_charityregistration_userregistration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='ItemId',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Price',
        ),
        migrations.AddField(
            model_name='item',
            name='Charity',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
