# Generated by Django 3.1.1 on 2020-09-08 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APPtest', '0003_auto_20200908_0337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='id',
        ),
        migrations.AddField(
            model_name='item',
            name='ItemID',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='OrderedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemName', models.CharField(max_length=200)),
                ('Quantity', models.IntegerField()),
                ('UserName', models.EmailField(max_length=254)),
                ('ItemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APPtest.item')),
            ],
        ),
    ]
