# Generated by Django 3.1.1 on 2020-09-08 22:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('APPtest', '0004_auto_20200909_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditem',
            name='OrderDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
